getcolor <- function(team){
	color <- switch(toupper(team),
				 "ARI" = "#A71930",
				 "ATL" = "#002F5F",
				 "BAL" = "#ED4C09",
				 "BOS" = "#C60C30",
				 "CHC" = "#003279",
				 "CHN" = "#003279",
				 "CHW" = "#000000",
				 "CHA" = "#000000",
				 "CIN" = "#C6011F",
				 "CLE" = "#D30335",
				 "COL" = "#333366",
				 "DET" = "#001742",
				 "HOU" = "#FF7F00",
				 "KCR" = "#74B4FA",
				 "KC" = "#74B4FA",
				 "KCA" = "#74B4FA",
				 "LAA" = "#B71234",
				 "ANA" = "#B71234",
				 "LAD" = "#083C6B",
				 "LAN" = "#083C6B",
				 "MIA" = "#F9423A",
				 "MIL" = "#92754C",
				 "MIN" = "#072754",
				 "MON" = "#EF4A4E",
				 "NYM" = "#FB4F14",
				 "NYN" = "#FB4F14",
				 "NYY" = "#1C2841",
				 "NYA" = "#1C2841",
				 "OAK" = "#003831",
				 #"OAK" = "green",
				 "PHI" = "#BA0C2F",
				 "PIT" = "#FDB829",
				 "SDN" = "#002147",
				 "SD" = "#002147",
				 "SDP" = "#002147",
				 #"SD" = "navy",
				 #"SDP" = "navy",
				 "SFG" = "#F2552C",
				 "SFN" = "#F2552C",
				 "SF" = "#F2552C",
				 "SEA" = "#005C5C",
				 "SLN" = "#C41E3A",
				 "STL" = "#C41E3A",
				 "TBD" = "#9ECEEE",
				 "TBR" = "#9ECEEE",
				 "TBA" = "#9ECEEE",
				 "TB" = "#9ECEEE",
				 "TEX" = "#BD1021",
				 "TOR" = "#003DA5",
				 "WAS" = "#BA122B",
				 "WSN" = "#BA122B",
				 "WSH" = "#BA122B"
	)
	if (is.null(color)){
		color = "#000000"
	} 
	return(color)
}

getcolor2 <- function(team){
     color <- switch(toupper(team),
                     "ARI" = "red",
                     "ATL" = "red",
                     "BAL" = "orange",
                     "BOS" = "blue",
                     "CHC" = "white",
                     "CHN" = "white",
                     "CHW" = "white",
                     "CHA" = "white",
                     "CIN" = "black",
                     "CLE" = "red",
                     "COL" = "purple",
                     "DET" = "orange",
                     "HOU" = "blue",
                     "KCR" = "white",
                     "KC" = "white",
                     "KCA" = "white",
                     "LAA" = "white",
                     "ANA" = "white",
                     "LAD" = "gray",
                     "LAN" = "gray",
                     "MIA" = "turquoise1",
                     "MIL" = "yellow",
                     "MIN" = "red",
                     "MON" = "blue",
                     "NYM" = "blue",
                     "NYN" = "blue",
                     "NYY" = "white",
                     "NYA" = "white",
                     "OAK" = "yellow",
                     "PHI" = "white",
                     "PIT" = "black",
                     "SDN" = "white",
                     "SD" = "white",
                     "SDP" = "white",
                     "SFG" = "black",
                     "SFN" = "black",
                     "SF" = "black",
                     "SEA" = "green",
                     "SLN" = "white",
                     "STL" = "white",
                     "TBD" = "navy",
                     "TBR" = "navy",
                     "TBA" = "navy",
                     "TB" = "navy",
                     "TEX" = "blue",
                     "TOR" = "white",
                     "WAS" = "navy",
                     "WSN" = "navy",
                     "WSH" = "navy"
     )
     if (is.null(color)){
          color = "#000000"
     } 
     return(color)
}