getcolor <- function(team){
     
	color <- switch(toupper(team),
				 "ARI" = "#A71930",
				 "ATL" = "#BA0C2F",
				 "BAL" = "#FC4C02",
				 "BOS" = "#C8102E",
				 "CHC" = "#005492",
				 "CHN" = "#005492",
				 #"CHN" = "blue",
				 "CHW" = "#000000",
				 "CHA" = "#000000",
				 "CIN" = "#C6011F",
				 "CLE" = "#0C2340",
				 "COL" = "#330072",
				 "DET" = "#0C2340",
				 "HOU" = "#002D62",
				 "KCR" = "#1A4784",
				 "KC" = "#1A4784",
				 "KCA" = "#1A4784",
				 "LAA" = "#B71234",
				 "ANA" = "#BA0021",
				 "LAD" = "#083C6B",
				 "LAN" = "#083C6B",
				 "MIA" = "#ED6F2E",
				 "MIL" = "#92754C",
				 "MIN" = "#0C2340",
				 "MON" = "#EF4A4E",
				 "NYM" = "#FC4C02",
				 "NYN" = "#FC4C02",
				 "NYY" = "#1C2841",
				 "NYA" = "#1C2841",
				 "OAK" = "#034638",
				 #"OAK" = "green",
				 "PHI" = "#BA0C2F",
				 "PIT" = "#FFC72C",
				 "SDN" = "#041E42",
				 "SD" = "#041E42",
				 "SDP" = "#041E42",
				 #"SD" = "navy",
				 #"SDP" = "navy",
				 "SFG" = "#F2552C",
				 "SFN" = "#F2552C",
				 "SF" = "#F2552C",
				 "SEA" = "#00685E",
				 "SLN" = "#BA0C2F",
				 #"SLN" = "red",
				 "STL" = "#BA0C2F",
				 "TBD" = "#9ECEEE",
				 "TBR" = "#9ECEEE",
				 "TBA" = "#9ECEEE",
				 "TB" = "#9ECEEE",
				 "TEX" = "#002D72",
				 "TOR" = "#134A8E",
				 "WAS" = "#BA122B",
				 "WSN" = "#BA122B",
				 "WSH" = "#BA122B"
	)
	if (is.null(color)){
		color = "#000000"
	} 
	return(color)
}

getcolor2 <- function(team){
     color <- switch(toupper(team),
                     "ARI" = "#E3D4AD",
                     "ATL" = "#0C2340",
                     "BAL" = "#000000",
                     "BOS" = "#0C2340",
                     "CHC" = "#ffffff",
                     "CHN" = "#ffffff",
                     #"CHN" = "white",
                     "CHW" = "#8A8D8F",
                     "CHA" = "#8A8D8F",
                     "CIN" = "black",
                     "CLE" = "#D50032",
                     "COL" = "#C4CED4",
                     "DET" = "#FA4616",
                     "HOU" = "#EB6E1F",
                     "KCR" = "#ffffff",
                     "KC" = "#ffffff",
                     "KCA" = "#ffffff",
                     "LAA" = "#ffffff",
                     "ANA" = "#ffffff",
                     "LAD" = "#A5ACAF",
                     "LAN" = "#A5ACAF",
                     "MIA" = "#0077C8",
                     "MIL" = "#85714D",
                     "MIN" = "#BA0C2F",
                     "MON" = "blue",
                     "NYM" = "#002D72",
                     "NYN" = "#002D72",
                     "NYY" = "white",
                     "NYA" = "white",
                     "OAK" = "#FFB81C",
                     "PHI" = "#003087",
                     "PIT" = "black",
                     "SDN" = "#A2AAAD",
                     "SD" = "#A2AAAD",
                     "SDP" = "#A2AAAD",
                     "SFG" = "#000000",
                     "SFN" = "#000000",
                     "SF" = "#000000",
                     "SEA" = "#0C2340",
                     "SLN" = "#FEDB00",
                     #"SLN" = "yellow",
                     "STL" = "#FEDB00",
                     "TBD" = "navy",
                     "TBR" = "navy",
                     "TBA" = "navy",
                     "TB" = "navy",
                     "TEX" = "#BA0C2F",
                     "TOR" = "#E8291C",
                     "WAS" = "navy",
                     "WSN" = "navy",
                     "WSH" = "navy"
     )
     if (is.null(color)){
          color = "#000000"
     } 
     return(color)
}